name: falnova
description: Kahve Falı ve Astroloji Platformu
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  riverpod: ^2.5.1
  
  # Navigation
  go_router: ^13.2.0
  
  # Model Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  
  # Network & API
  dio: ^5.4.0
  supabase_flutter: ^2.3.4
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^18.0.1
  
  # UI Components
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  flutter_markdown: ^0.6.20
  
  # Utils
  logger: ^2.0.2+1
  intl: ^0.19.0
  share_plus: ^10.1.4
  path_provider: ^2.1.2
  http: ^1.2.0
  loading_animation_widget: ^1.2.0+4
  badges: ^3.1.2
  timezone: ^0.9.2
  flutter_launcher_icons: ^0.14.3
  package_info_plus: ^8.1.3
  get: ^4.6.6
  transparent_image: ^2.0.1
  google_generative_ai: ^0.4.0
  logging: ^1.3.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  flutter_native_splash: ^2.3.10
  sweph: ^3.2.1+2.10.3
  permission_handler: ^11.3.1
  path: ^1.8.3
  vector_math: ^2.1.4
  
  # Image Processing
  camera: ^0.10.5+5
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/images/default_avatar.png
    - assets/images/google_logo.png
    - assets/ephe/
    - assets/ephe/seas_18.se1
    - assets/ephe/semo_18.se1
    - assets/ephe/sepl_18.se1
    - assets/ephe/sefstars.txt
    - assets/ephe/seasnam.txt
    - assets/ephe/seorbel.txt
    - assets/ephe/seleapsec.txt

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#1A1B25"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter_native_splash:
  color: "#F3E5F5"
  image: assets/splash/splash_logo.png
  android: true
  ios: true
  
  android_12:
    color: "#F3E5F5"
    image: assets/splash/splash_logo.png
    icon_background_color: "#F3E5F5"
    
  web: false
