// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYECp1zDn3mgPr21uoUv39ygawMfLQQE0',
    appId: '1:430048320125:web:7a6d695a830cf0b8872f14',
    messagingSenderId: '430048320125',
    projectId: 'falnova',
    authDomain: 'falnova.firebaseapp.com',
    storageBucket: 'falnova.firebasestorage.app',
    measurementId: 'G-V80M6SE51W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKIyI8J-Pm44cY9M1mc-0VylNMflWLZgE',
    appId: '1:430048320125:android:d5b49c6cd2def956872f14',
    messagingSenderId: '430048320125',
    projectId: 'falnova',
    storageBucket: 'falnova.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD8BCnIB-FvhBa0Krqkp8GrA3KnAHKYUE',
    appId: '1:430048320125:ios:37b542211d514db8872f14',
    messagingSenderId: '430048320125',
    projectId: 'falnova',
    storageBucket: 'falnova.firebasestorage.app',
    iosBundleId: 'com.example.falnova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD8BCnIB-FvhBa0Krqkp8GrA3KnAHKYUE',
    appId: '1:430048320125:ios:37b542211d514db8872f14',
    messagingSenderId: '430048320125',
    projectId: 'falnova',
    storageBucket: 'falnova.firebasestorage.app',
    iosBundleId: 'com.example.falnova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYECp1zDn3mgPr21uoUv39ygawMfLQQE0',
    appId: '1:430048320125:web:168e9e586c54bfd0872f14',
    messagingSenderId: '430048320125',
    projectId: 'falnova',
    authDomain: 'falnova.firebaseapp.com',
    storageBucket: 'falnova.firebasestorage.app',
    measurementId: 'G-ZN5YQ2HS7V',
  );

}